version: '3'
networks:
  external:
  internal:
services:
  nginx:
    image: nginx:latest
    expose:
        - 80
    labels:
        - traefik.enable=true
        - traefik.http.middlewares.streamforce_headers.headers.customrequestheaders.Origin=
        - traefik.http.middlewares.streamforce_headers.headers.sslredirect=true
        - traefik.http.middlewares.streamforce_redirect.redirectregex.permanent=true
        - traefik.http.middlewares.streamforce_redirect.redirectregex.regex=^http://(.*)
        - traefik.http.middlewares.streamforce_redirect.redirectregex.replacement=https://$$1
        - traefik.http.routers.streamforce.entrypoints=web
        - traefik.http.routers.streamforce.middlewares=streamforce_headers@docker
        - traefik.http.routers.streamforce.rule=HostHeader(`streamforce.oddnetwork.org`)
        - traefik.http.routers.streamforce.tls=true
        - traefik.http.routers.streamforce_redirect.entrypoints=web
        - traefik.http.routers.streamforce_redirect.middlewares=streamforce_redirect@docker
        - traefik.http.routers.streamforce_redirect.rule=HostHeader(`streamforce.oddnetwork.org`)
        - traefik.http.services.streamforce.loadbalancer.sticky=true
        - traefik.http.services.streamforce.loadbalancer.sticky.cookie.httponly=true
        - traefik.http.services.streamforce.loadbalancer.sticky.cookie.secure=true
    networks:
        - external
        - internal
    volumes:
        - ./static:/usr/share/nginx/html
  traefik:
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=streamforce_external
    depends_on:
      - nginx
    image: traefik:latest
    ports:
      - 5001:80
      - 5002:8080
    networks:
      - external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro